baseURL = 'https://pavelstefanov.su/'
title = 'Павел Стефанов'
theme = 'PaperMod'
paginate = 5

enableRobotsTXT = true

googleAnalytics = 'G-PBNL09TJ6E'

# pygmentsUseClasses = true


[params]
env = 'production'
title = 'Павел Стефанов'
description = "Личный блог"
keywords = [ 'Блог', 'Технологии', 'Менеджмент', 'Психология']
DateFormat = '02.01.2006'
defaultTheme = 'auto'
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = '/favicon/favicon.ico'
  favicon16x16 = '/favicon/favicon-16x16.png'
  favicon32x32 = '/favicon/favicon-32x32.png'
  apple_touch_icon = '/favicon/apple-touch-icon.png'

  [params.label]
  text = 'Павел Стефанов'

  [params.homeInfoParams]
  Title = 'Привет👋 Я Павел Стефанов!'
  Content = 'Я занимаюсь разработкой ПО и здесь буду писать о своей жизни и том, что мне интересно'

  [[params.socialIcons]]
  name = 'twitter'
  url = 'https://twitter.com/Droppi_nsk'

  [[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/PavelStefanov'

  [[params.socialIcons]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/stefanovpavel'

  [[params.socialIcons]]
  name = 'rss'
  url = 'index.xml'



[params.analytics.google]
SiteVerificationTag = 'XYZabc'

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ 'title', 'permalink', 'summary', 'content' ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = 'search'
name = 'поиск'
url = '/search'
weight = 10

[[menu.main]]
identifier = 'search'
name = 'поиск'
url = '/search'
weight = 10

[markup.highlight]
noClasses = false
